--TRANSACCION DE LA TABLA CONTRATO
CREATE OR REPLACE PROCEDURE totalsueldo()
LANGUAGE PLPGSQL
AS $$
BEGIN
UPDATE CONTRATO SET TOTAL_SUELDO=SUELDO_CONTRATO-SEGURO;
IF(SELECT MAX(ID_CONTRATO) FROM CONTRATO WHERE TOTAL_SUELDO IS NULL)>0 THEN
COMMIT;
ELSE
IF(SELECT MAX(ID_CONTRATO) FROM CONTRATO WHERE TOTAL_SUELDO IS NULL)<=0 THEN
ROLLBACK;
END IF;
END IF;
END
$$;

INSERT INTO CONTRATO VALUES (2,'20-02-2020','3 AÑOS',500.00,50.00)
CALL totalsueldo();
SELECT* FROM CONTRATO

DELETE FROM CONTRATO WHERE ID_CONTRATO=2;
DROP TABLE CONTRATO;
DROP PROCEDURE totalsueldo();

--TRANSACCION DE LA TABLA HORARIO
CREATE OR REPLACE PROCEDURE totalhoraextra()
LANGUAGE PLPGSQL
AS $$
BEGIN
UPDATE HORARIO SET TOTAL_HORA=PAGO_HORAEXTRA*HORA_EXTRAS;
IF(SELECT MAX(ID_HORARIO) FROM HORARIO WHERE TOTAL_HORA IS NULL)>0 THEN
COMMIT;
ELSE
IF(SELECT MAX(ID_HORARIO) FROM HORARIO WHERE TOTAL_HORA IS NULL)<=0 THEN
ROLLBACK;
END IF;
END IF;
END
$$;



INSERT INTO HORARIO VALUES (20,21,'08:00','16:00',2,50)
SELECT* FROM HORARIO
CALL totalhoraextra();

DELETE FROM HORARIO WHERE ID_HORARIO=20;
DROP TABLE HORARIO;
DROP PROCEDURE totalhoraextra();



